INCLUDE := $(COMMON)/include
SRC := $(COMMON)/sample

ifeq ($(OS),Windows_NT)
SOURCEDIRS	:= $(SRC)
INCLUDEDIRS	:= $(INCLUDE)
else
SOURCEDIRS	:= $(shell find $(SRC) -type d)
INCLUDEDIRS	:= $(shell find $(INCLUDE) -type d)
endif

SOURCES	 += $(SRC)/$(SAMPLE_FILE).c
INCLUDES += $(patsubst %,-I%, $(INCLUDEDIRS:%/=%))

C_DEFS +=
